title: Tlog
author: @Tyler887
description: > My Test Blog from GitHub
theme: minima

# social links

github_username:  Tyler887 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
